// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------- //
// delayedinterrupt //
// ---------------- //

#define delayedinterrupt_wrap_target 0
#define delayedinterrupt_wrap 6

static const uint16_t delayedinterrupt_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0xe041, //  1: set    y, 1                       
    0xe03f, //  2: set    x, 31                      
    0x1f43, //  3: jmp    x--, 3                 [31]
    0x1f82, //  4: jmp    y--, 2                 [31]
    0xc701, //  5: irq    nowait 1               [7] 
    0xc041, //  6: irq    clear 1                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program delayedinterrupt_program = {
    .instructions = delayedinterrupt_program_instructions,
    .length = 7,
    .origin = -1,
};

static inline pio_sm_config delayedinterrupt_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + delayedinterrupt_wrap_target, offset + delayedinterrupt_wrap);
    return c;
}
#endif
