// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// pixelreader //
// ----------- //

#define pixelreader_wrap_target 0
#define pixelreader_wrap 23

static const uint16_t pixelreader_program_instructions[] = {
            //     .wrap_target
    0xe033, //  0: set    x, 19                      
    0xa0c1, //  1: mov    isr, x                     
    0xe02f, //  2: set    x, 15                      
    0x4024, //  3: in     x, 4                       
    0xa046, //  4: mov    y, isr                     
    0xe03f, //  5: set    x, 31                      
    0x00c5, //  6: jmp    pin, 5                     
    0x00c5, //  7: jmp    pin, 5                     
    0x00c5, //  8: jmp    pin, 5                     
    0x00c5, //  9: jmp    pin, 5                     
    0x00c5, // 10: jmp    pin, 5                     
    0x0046, // 11: jmp    x--, 6                     
    0xa0c1, // 12: mov    isr, x                     
    0x20a6, // 13: wait   1 pin, 6                   
    0x8060, // 14: push   iffull block               
    0x4964, // 15: in     null, 4                [9] 
    0x4006, // 16: in     pins, 6                    
    0x2026, // 17: wait   0 pin, 6                   
    0xaa42, // 18: nop                           [10]
    0x4006, // 19: in     pins, 6                    
    0x008d, // 20: jmp    y--, 13                    
    0x8060, // 21: push   iffull block               
    0xc500, // 22: irq    nowait 0               [5] 
    0xc040, // 23: irq    clear 0                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pixelreader_program = {
    .instructions = pixelreader_program_instructions,
    .length = 24,
    .origin = -1,
};

static inline pio_sm_config pixelreader_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pixelreader_wrap_target, offset + pixelreader_wrap);
    return c;
}
#endif
