/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Sat Oct 18 23:55:35 2025 */

/* parameterized module instance */
PLLHDMI __ (.CLKI( ), .CLKOP( ), .CLKOS( ));
