// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// lightswitcher //
// ------------- //

#define lightswitcher_wrap_target 3
#define lightswitcher_wrap 14

static const uint16_t lightswitcher_program_instructions[] = {
    0xf027, //  0: set    x, 7            side 1     
    0xb0c1, //  1: mov    isr, x          side 1     
    0x5024, //  2: in     x, 4            side 1     
            //     .wrap_target
    0xb026, //  3: mov    x, isr          side 1     
    0x30c4, //  4: wait   1 irq, 4        side 1     
    0x0f45, //  5: jmp    x--, 5          side 0 [15]
    0xb026, //  6: mov    x, isr          side 1     
    0x30c4, //  7: wait   1 irq, 4        side 1     
    0x0748, //  8: jmp    x--, 8          side 0 [7] 
    0xb026, //  9: mov    x, isr          side 1     
    0x30c4, // 10: wait   1 irq, 4        side 1     
    0x034b, // 11: jmp    x--, 11         side 0 [3] 
    0xb026, // 12: mov    x, isr          side 1     
    0x30c4, // 13: wait   1 irq, 4        side 1     
    0x014e, // 14: jmp    x--, 14         side 0 [1] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program lightswitcher_program = {
    .instructions = lightswitcher_program_instructions,
    .length = 15,
    .origin = -1,
};

static inline pio_sm_config lightswitcher_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + lightswitcher_wrap_target, offset + lightswitcher_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif
