// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// outshifter //
// ---------- //

#define outshifter_wrap_target 0
#define outshifter_wrap 11

static const uint16_t outshifter_program_instructions[] = {
            //     .wrap_target
    0x90a0, //  0: pull   block           side 0     
    0x600c, //  1: out    pins, 12                   
    0xa042, //  2: nop                               
    0x6064, //  3: out    null, 4                    
    0xb842, //  4: nop                    side 1     
    0xa042, //  5: nop                               
    0xb042, //  6: nop                    side 0     
    0x600c, //  7: out    pins, 12                   
    0xa042, //  8: nop                               
    0x6064, //  9: out    null, 4                    
    0xb842, // 10: nop                    side 1     
    0xa042, // 11: nop                               
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program outshifter_program = {
    .instructions = outshifter_program_instructions,
    .length = 12,
    .origin = -1,
};

static inline pio_sm_config outshifter_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + outshifter_wrap_target, offset + outshifter_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif
