// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// outshifter //
// ---------- //

#define outshifter_wrap_target 0
#define outshifter_wrap 6
#define outshifter_pio_version 0

static const uint16_t outshifter_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xb042, //  1: nop                    side 0
    0x600c, //  2: out    pins, 12
    0x7864, //  3: out    null, 4         side 1
    0xb042, //  4: nop                    side 0
    0x600c, //  5: out    pins, 12
    0x7864, //  6: out    null, 4         side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program outshifter_program = {
    .instructions = outshifter_program_instructions,
    .length = 7,
    .origin = -1,
//    .pio_version = outshifter_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config outshifter_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + outshifter_wrap_target, offset + outshifter_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
static inline void outshifter_program_init(PIO pio, uint sm, uint offset, uint pins, uint clkpin )
{	
	pio_sm_config c = outshifter_program_get_default_config(offset);
  	pio_sm_set_consecutive_pindirs(pio, sm, pins, 3, true);	
	sm_config_set_out_pins(&c, pins, 12); // rgb1, rgb2
    sm_config_set_sideset_pins(&c, clkpin); // clkpin
	sm_config_set_clkdiv(&c, 1.0);
	pio_sm_init(pio, sm, offset, &c);
	pio_sm_set_enabled(pio, sm, true);
}

#endif

